config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :customers
  resources :comments
  resources :npi_statuses
  resources :carriers do
    resources :contacts
  end
  resources :containers do
    member do
      put 'empty'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/customer_new',  to: 'customers#new',  via: 'get'
  match '/comment_new',   to: 'comments#new',   via: 'get'
  match '/npi_status_new', to: 'npi_statuses#new',  via: 'get'
  match '/carrier_new', to: 'carriers#new',     via: 'get'
  match '/container_new', to: 'containers#new', via: 'get'   

  

end

app/models/carrier.rb
class Carrier < ActiveRecord::Base
	has_many :containers
	has_many :contacts, dependent: :destroy

	# Validation
	validates :name, presence: true, length: {maximum: 50}
	
end

app/controllers/carriers_controller.rb
class CarriersController < ApplicationController

  def index
    @carriers = Carrier.all
  end

  def show
	@carrier = Carrier.find(params[:id])
  end

  def new
  	@carrier = Carrier.new
  end

  def create
    @carrier = Carrier.new(carrier_params)
    if @carrier.save
      #sign_in @user - removed so new user isn't logged in
      flash[:success] = "Carrier Created: " + @carrier.name
      redirect_to carriers_url
    else
      render 'new'
    end
  end

  def edit
    @carrier = Carrier.find(params[:id])
  end

  def update
    @carrier = Carrier.find(params[:id])
    if @carrier.update_attributes(carrier_params)
      flash[:success] = @carrier.name + " updated"
      redirect_to carriers_url
    else
      render 'edit'
    end
  end

  def destroy
    @carrier = Carrier.find(params[:id])
    Carrier.find(params[:id]).destroy
    flash[:success] = @carrier.name + " has been deleted."
    redirect_to carriers_url
  end 

private

    def carrier_params
      # might need to remove :role_id from this - see section 9.4.2
      # "Revisiting strong parameters"
      params.require(:carrier).permit(:name)
    end

end

app/helpers/carriers_helper.rb
module CarriersHelper
end

app/views/carriers/edit.html.erb
<% provide(:title, 'Edit carrier') %>
<div class="page-header">
  <h3><i class="fa fa-truck"></i> Update carrier</h3>
</div>

<div class="row">
    <div class="col-lg-6">
      <%= bootstrap_form_for(@carrier) do |f| %>
      <div class="panel panel-default">
        <div class="panel-body">        
          <%= f.text_field :name %>
        </div>
        <div class="panel-footer text-right">
          <%= f.submit "Save changes", class: "btn btn-primary" %>
          <%= link_to "Cancel", carriers_path, class: "btn btn-danger" %>
        </div>
      </div>
      <% end %>
  </div>
</div>  

app/views/carriers/index.html.erb
<% provide(:title, 'All carriers') %>
<div class="page-header">
  <h3><i class="fa fa-truck"></i> All carriers</h3>
</div>

<table class="table table-striped table-bordered" id="carriers">
<thead>	
	<tr>
		<th>Carrier Name</th>
		<th>Contacts</th>		
		<th>Edit</th>
		<th>Delete</th>
	</tr>
</thead>
<tbody>
<% @carriers.each do |carrier| %>
	<tr>
		<td><%= carrier.name %></td>
		<td class="text-center"><%= link_to carrier_contacts_url(carrier), class: "btn btn-primary btn-xs"  do %><i class="fa fa-user"></i><% end %>
		</td>
		<td class="text-center"><%= link_to edit_carrier_path(carrier), class: "btn btn-primary btn-xs"  do %><i class="fa fa-pencil-square-o"></i><% end %>
		</td>
		<td class="text-center">
			<%= link_to carrier, method: :delete, data: { confirm: "Please confirm you want to delete " + carrier.name},
				  class: "btn btn-danger btn-xs" do %>
				<i class="fa fa-trash-o"></i><% end %>
		</td>
	</tr>
<% end %>
</table>

app/views/carriers/new.html.erb
<% provide(:title, 'Create Carrier') %>
<div class="page-header">
  <h3><i class="fa fa-truck"></i> Create New Carrier</h3>
</div>

<div class="row">
    <div class="col-lg-6">
      <%= bootstrap_form_for(@carrier) do |f| %>
      <div class="panel panel-default">
        <div class="panel-body">        
          <%= f.text_field :name %>
        </div>
        <div class="panel-footer text-right">
          <%= f.submit "Create Carrier", class: "btn btn-primary" %>
          <%= link_to "Cancel", carriers_path, class: "btn btn-danger" %>
        </div>
      </div>
      <% end %>
  </div>
</div>  

app/views/carriers/show.html.erb
<% provide(:title, @carrier.name) %>
<div class="page-header">
  <h3><i class="fa fa-truck"></i> Carrier profile</h3>
</div>