config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :customers
  resources :comments
  resources :npi_statuses
  resources :carriers do
    resources :contacts
  end
  resources :containers do
    member do
      put 'empty'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/customer_new',  to: 'customers#new',  via: 'get'
  match '/comment_new',   to: 'comments#new',   via: 'get'
  match '/npi_status_new', to: 'npi_statuses#new',  via: 'get'
  match '/carrier_new', to: 'carriers#new',     via: 'get'
  match '/container_new', to: 'containers#new', via: 'get'   

  

end

app/models/container.rb
class Container < ActiveRecord::Base
	belongs_to :carrier
	belongs_to :npi_status
	belongs_to :customer
	belongs_to :comment

	default_scope -> { order('date DESC') }

	# Validation
	VALID_CONTAINER_REGEX = /[A-Z]{4}[0-9]{7}/
	validates :container_number, presence: true, format: {with: VALID_CONTAINER_REGEX,
		message: "Valid container number is 4 alpha followed by 7 numeric. For example
		ABCD1234567"}, length: { maximum: 11 }
	validates :date, presence: true
	validates :bay, numericality: {only_integer: true, less_than_or_equal_to: 40}
	validates :carrier_id, presence: true
	validates :customer_id, presence: true
	

end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController

  def index
    @containers = Container.all
  end

  def new
  	@container = Container.new
  end
  
  def create
	@container = Container.new(container_params)
	if @container.save
      #sign_in @user - removed so new user isn't logged in
      flash[:success] = "Container log Created: " + @container.container_number
      redirect_to containers_url
    else
      render 'new'
    end
  end

  def edit
    @container = Container.find(params[:id])
  end

  def update
    @container = Container.find(params[:id])
    if @container.update_attributes(container_params)
      flash[:success] = @container.container_number + " updated"
      redirect_to containers_url
    else
      render 'edit'
    end
  end

  def destroy
    @container = Container.find(params[:id])
    Container.find(params[:id]).destroy
    flash[:warning] = @container.container_number + " has been deleted."
    redirect_to containers_url
  end

  def empty
    @container = Container.find(params[:id])
    @container.update_attribute(:mt_email_sent, true)
    # commented below line to stop email being sent
    #ContactMailer.confirm_email(@container.carrier.contacts.find(2)).deliver
    flash[:success] = @container.container_number + " is now empty.
     A confirmation email has been sent."
    redirect_to containers_url
  end

  private

    def container_params
      # "Revisiting strong parameters"
      params.require(:container).permit(:container_number, :date, :bay, :door_orientation,
      	:carrier_id, :do_received, :entry_number, :ship_voyage, :npi_status_id,
      	:config_received, :priority, :doc_date, :customer_id, :devan_date, :mt_email_sent,
      	:text_comment, :comment_id)
    end

end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/views/containers/edit.html.erb
<% provide(:title, 'Edit container') %>
<div class="page-header">
  <h3><i class="fa fa-cube"></i> Edit container</h3>
</div>

<div class="row">
  <div class="col-lg-12">
    <%= bootstrap_form_for(@container) do |f| %>      
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="row">
            <div class="col-md-6">
              <%= f.text_field :container_number %>
              <%= f.select :customer_id, Customer.all.collect { |c| [c.acc_name, c.id]},
                { include_blank: true, default: nil } %>
              <%= f.select :priority, options_for_select(["High", "Medium", "Low"]) %>  
      				<%= f.text_field :bay %>
          		<%= f.text_field :entry_number %>
          		<%= f.select :npi_status_id, NpiStatus.all.collect { |n| [n.name, n.id]} %>
              <div class="row">
                <div class="col-md-6">
                  <%= f.label :do_received do %>
                    D.O. Received
                    <%= f.check_box :do_received %>
                  <% end %>
                </div>
                <div class="col-md-6">
                  <%= f.label :config_received do %>
                    Configuration Received
                  <%= f.check_box :config_received %>
                  <% end %>
                </div>    
              </div>
            </div>
            <div class="col-md-6">
              <%= f.date_field :date %>
              <%= f.select :carrier_id, Carrier.all.collect { |c| [c.name, c.id]},
                { include_blank: true, default: nil } %>
              <%= f.text_field :ship_voyage %>
      				<%= f.select :door_orientation, options_for_select(["Doors Front", "Doors Rear"]) %>
              <%= f.date_field :doc_date %>
              <%= f.date_field :devan_date %>
              <%= f.select :comment_id, Comment.all.collect { |c| [c.comment_description, c.id]},
                { include_blank: true, default: nil } %>
            </div>
            <div class="col-md-12">
              <%= f.text_area :text_comment %>
            </div>
          </div> <!-- row -->
        </div>
        <div class="panel-footer text-right">
          <%= f.submit "Update Container Log", class: "btn btn-primary" %>
          <%= link_to "Cancel", containers_path, class: "btn btn-danger" %>
        </div>
      </div>
    <% end %>
	</div> 
</div> 

app/views/containers/index.html.erb
<% provide(:title, 'All containers') %>
<div class="page-header">
  <h3><i class="fa fa-cube"></i> All containers</h3>
</div>

<table class="table table-striped table-bordered" id="containers">
<thead>	
	<tr>
		<th>Container Num</th>
		<th>Date</th>
		<th>Customer</th>		
		<th>Carrier</th>
		<th>Priority</th>
		<th>Empty</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>
</thead>
<tbody>
	<% @containers.each do |container| %>
		<tr class="<%= 'danger' if container.priority == 'High' %>">
			<td><%= container.container_number %></td>
			<td><%= container.date.strftime("%d/%m/%Y") %></td>
			<td><%= container.customer.acc_name %></td>
			<td><%= container.carrier.name %></td>
			<td><%= container.priority %></td>
			<% if !container.mt_email_sent %>
				<td class="text-center"><%= link_to empty_container_path(container), method: :put, class: "btn btn-info btn-xs", data: { toggle: "dropdown"}, data: { placement: "left"}, title: "Set container to devanned"  do %>
					<i class="fa fa-external-link"></i><% end %></td>		
			<% else %>
				<td class="text-center">
					<i class="fa fa-check-square-o"></i>
				</td>	
			<% end %>
			<td class="text-center"><%= link_to edit_container_path(container), class: "btn btn-primary btn-xs"  do %><i class="fa fa-pencil-square-o"></i><% end %></td>
			<td class="text-center"><%= link_to container, method: :delete, data: { confirm: "Please confirm you want to delete " + container.container_number},
					  class: "btn btn-danger btn-xs" do %>
					<i class="fa fa-trash-o"></i><% end %></td>
		</tr>
	<% end %>
</table>

app/views/containers/new.html.erb
<% provide(:title, 'New container') %>
<div class="page-header">
  <h3><i class="fa fa-pencil-square-o"></i> Create New Container</h3>
</div>

<div class="row">
  <div class="col-lg-12">
    <%= bootstrap_form_for(@container) do |f| %>
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="row">
            <div class="col-md-6">
              <%= f.text_field :container_number %>
              <%= f.select :customer_id, Customer.all.collect { |c| [c.acc_name, c.id]},
                { include_blank: true, default: nil } %>
              <%= f.select :priority, options_for_select(["High", "Medium", "Low"]) %>  
              <%= f.text_field :bay %>
              <%= f.text_field :entry_number %>
              <%= f.select :npi_status_id, NpiStatus.all.collect { |n| [n.name, n.id]} %>
              <div class="row">
                <div class="col-md-6">
                  <%= f.label :do_received do %>
                    D.O. Received
                    <%= f.check_box :do_received %>
                  <% end %>
                </div>
                <div class="col-md-6">
                  <%= f.label :config_received do %>
                    Configuration Received
                  <%= f.check_box :config_received %>
                  <% end %>
                </div>    
              </div>
            </div>
            <div class="col-md-6">
              <%= f.date_field :date, placeholder: "dd/mm/yyyy" %>
              <%= f.select :carrier_id, Carrier.all.collect { |c| [c.name, c.id]},
                { include_blank: true, default: nil } %>
              <%= f.text_field :ship_voyage %>
              <%= f.select :door_orientation, options_for_select(["Doors Front", "Doors Rear"]) %>
              <%= f.date_field :doc_date, placeholder: "dd/mm/yyyy" %>
              <%= f.date_field :devan_date, placeholder: "dd/mm/yyyy" %>
              <%= f.select :comment_id, Comment.all.collect { |c| [c.comment_description, c.id]},
                { include_blank: true, default: nil } %>
            </div>
            <div class="col-md-12">
              <%= f.text_area :text_comment %>
            </div>
          </div> <!-- row -->
        </div>
        <div class="panel-footer text-right">
          <%= f.submit "Create Container Log", class: "btn btn-primary" %>
          <%= link_to "Cancel", containers_path, class: "btn btn-danger" %>
        </div>
      </div>
    <% end %>
	</div> 
</div> 