config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :customers
  resources :comments
  resources :npi_statuses
  resources :carriers do
    resources :contacts
  end
  resources :containers do
    member do
      put 'empty'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/customer_new',  to: 'customers#new',  via: 'get'
  match '/comment_new',   to: 'comments#new',   via: 'get'
  match '/npi_status_new', to: 'npi_statuses#new',  via: 'get'
  match '/carrier_new', to: 'carriers#new',     via: 'get'
  match '/container_new', to: 'containers#new', via: 'get'   

  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :carrier
	before_save { self.first_name = first_name.capitalize }
	before_save { self.last_name = last_name.capitalize }
	before_save { self.email = email.downcase }

	#sort
	default_scope -> { order('last_name, first_name') }

	# Validation
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :first_name, presence: true, length: {maximum: 50}
	validates :last_name, presence: true, length: {maximum: 50}
	validates :email, presence: true, format: {with: VALID_EMAIL_REGEX},
		uniqueness: { case_sensitive: false }
	validates :carrier_id, presence: true
	
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	before_filter :load_carrier

  def new
	 @contact = @carrier.contacts.new
  end

  def create
    @contact = @carrier.contacts.new(contact_params)
    if @contact.save
      flash[:success] = "Contact Created: " + @contact.first_name + " " +
        @contact.last_name
      redirect_to carrier_contacts_url(@carrier)
    else
      render 'new'
    end
  end

  def show

  end

  def index
	 @contacts = @carrier.contacts.all
  end

  def edit
    @contact = @carrier.contacts.find(params[:id])
  end

  def update
    @contact = @carrier.contacts.find(params[:id])
    if @contact.update_attributes(contact_params)
      flash[:success] = @contact.first_name + " " + @contact.last_name + " updated"
      redirect_to carrier_contacts_url(@carrier)
    else
      render 'edit'
    end 
  end

  def destroy
    @contact = @carrier.contacts.find(params[:id])
    @carrier.contacts.find(params[:id]).destroy
    flash[:success] = @contact.first_name + " " + @contact.last_name + " has been deleted."
    redirect_to carrier_contacts_url(@carrier)
  end

  private

  	def contact_params
		params.require(:contact).permit(:first_name, :last_name, :email,
										:carrier_id, :email_notification)
  	end

  	def load_carrier
  		@carrier = Carrier.find(params[:carrier_id])
  	end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/edit.html.erb
<% provide(:title, 'Edit Contact') %>
<div class="page-header">
  <h3><i class="fa fa-user"></i> Edit Contact</h3>
</div>

<div class="row">
    <div class="col-lg-6">
      <%= bootstrap_form_for([@carrier, @contact]) do |f| %>
        <div class="panel panel-default">
          <div class="panel-body">        
            <%= f.text_field :first_name %>
            <%= f.text_field :last_name %>
            <%= f.email_field :email %>
            <%= f.label :email_notification do %>
              Send email notification
              <%= f.check_box :email_notification %>
            <% end %>
          </div>
          <div class="panel-footer text-right">
            <%= f.submit "Save Changes", class: "btn btn-primary" %>
            <%= link_to "Cancel", carrier_contacts_path(@carrier), class: "btn btn-danger" %>
          </div>
        </div>
      <% end %>     
  </div>
</div>  

app/views/contacts/index.html.erb
<% provide(:title, @carrier.name) %>
<div class="page-header">
	<h3><i class="fa fa-truck"></i> <%= "#{@carrier.name} - Contacts" %></h3>
</div>

	<%= link_to "New Contact", new_carrier_contact_path(@carrier), class: "btn btn-info" %><br>
	<br>
	<table class="table table-striped table-bordered" id="contacts">
	<thead>	
		<tr>
			<th>First Name</th>
			<th>Last Name</th>		
			<th>Email</th>
			<th>Send Email</th>
			<th>Edit</th>
			<th>Delete</th>
		</tr>
	</thead>
	<tbody>
	<%	@contacts.each do |contact| %>
		<tr>
			<td><%= contact.first_name %></td>
			<td><%= contact.last_name %></td>
			<td><%= contact.email %></td>
			<td><%= contact.email_notification %></td>
			<td class="text-center"><%= link_to edit_carrier_contact_path(@carrier, contact), class: "btn btn-primary btn-xs"  do %><i class="fa fa-pencil-square-o"></i><% end %></td>
			<td class="text-center"><%= link_to [@carrier, contact], method: :delete, data: { confirm: "Please confirm you want to delete " + contact.first_name + " " + contact.last_name},
				  class: "btn btn-danger btn-xs" do %>
				<i class="fa fa-trash-o"></i><% end %></td>
		</tr>
	<% end %>
	</table>

app/views/contacts/new.html.erb
<% provide(:title, 'Create Contact') %>
<div class="page-header">
  <h3><i class="fa fa-user"></i> Create New Contact</h3>
</div>

<div class="row">
    <div class="col-lg-6">
      <%= bootstrap_form_for([@carrier, @contact]) do |f| %>
        <div class="panel panel-default">
          <div class="panel-body">        

            <%= f.text_field :first_name %>
            <%= f.text_field :last_name %>
            <%= f.email_field :email %>
            <%= f.label :email_notification do %>
              Send email notification
              <%= f.check_box :email_notification %>
            <% end %>
          </div>
          <div class="panel-footer text-right">
            <%= f.submit "Create Contact", class: "btn btn-primary" %>
            <%= link_to "Cancel", carrier_contacts_path(@carrier), class: "btn btn-danger" %>
          </div>
        </div>
      <% end %>      
  </div>
</div>  