config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :customers
  resources :comments
  resources :npi_statuses
  resources :carriers do
    resources :contacts
  end
  resources :containers do
    member do
      put 'empty'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/customer_new',  to: 'customers#new',  via: 'get'
  match '/comment_new',   to: 'comments#new',   via: 'get'
  match '/npi_status_new', to: 'npi_statuses#new',  via: 'get'
  match '/carrier_new', to: 'carriers#new',     via: 'get'
  match '/container_new', to: 'containers#new', via: 'get'   

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "Container Log", root_path %>
    by Andy Reid
  </small>

</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "TNL Distribution - Container Log",    root_path, class: "navbar-brand" %>
      <!-- <a class="navbar-brand"><%= link_to "Sample app", '#', id: "logo" %></a> -->
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav pull-right">

          <% if signed_in? %>
            <li><%= link_to "About",   about_path %></li>
            <li><%= link_to "Help",    help_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
              <ul class="dropdown-menu pull-right">
                <li><%= link_to current_user do %>
                      <i class="fa fa-user"></i>Profile
                    <% end %>
                </li>
                <li><%= link_to edit_user_path(current_user) do %>
                      <i class="fa fa-cog"></i>Settings
                    <% end %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to signout_path, method: "delete" do %>
                    <i class="fa fa-sign-out"></i>Sign Out
                  <% end %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<nav class="sidebar-nav">
        <div class="center sidebar-user">
      <strong><%= current_user.name.upcase %></strong><br>
      <em><%= current_user.job_title %></em>
    </div>
  <ul id="side-menu">

    <li class="<%= 'active' if params[:controller] == 'containers' %>">
      <a href="#">
        <span class="sidebar-nav-item-icon fa fa-cube fa-lg"></span>
        <span class="sidebar-nav-item">Container Log</span>
        <span class="fa arrow"></span>
      </a>
      <ul>
        <li>
          <%= link_to containers_path do %>
            <i class="sidebar-nav-item-icon fa fa-cubes"></i>All Containers
          <% end %>
        </li>
        <li>
          <%= link_to container_new_path do %>
             <i class="sidebar-nav-item-icon fa fa-pencil-square-o"></i>New Container Log 
          <% end %>
        </li>
      </ul>
    </li>
    <li class="<%= 'active' if params[:controller] == 'customers' %>">
      <a href="#">
        <span class="sidebar-nav-item-icon fa fa-user fa-lg"></span>
        <span class="sidebar-nav-item">Customer</span>
        <span class="fa arrow"></span>
      </a>
      <ul>
        <li>
          <%= link_to customers_path do %>
            <i class="sidebar-nav-item-icon fa fa-users"></i>All Customers
          <% end %>
        </li>
        <li>
          <%= link_to customer_new_path do %>
             <i class="sidebar-nav-item-icon fa fa-pencil-square-o"></i>New Customer 
          <% end %>
        </li>
      </ul>
    </li>
    <li class="<%= 'active' if params[:controller] == 'carriers' or 
      params[:controller] == 'contacts' %>">
      <a href="#">
        <span class="sidebar-nav-item-icon fa fa-truck fa-lg"></span>
        <span class="sidebar-nav-item">Carrier</span>
        <span class="fa arrow"></span>
      </a>
      <ul>
        <li>
          <%= link_to carriers_path do %>
            <i class="sidebar-nav-item-icon fa fa-truck"></i>All Carriers
          <% end %>
        </li>
        <li>
          <%= link_to carrier_new_path do %>
             <i class="sidebar-nav-item-icon fa fa-pencil-square-o"></i>New Carrier 
          <% end %>
        </li>
      </ul>
    </li>
    
    <!-- test to see if admin user to display this menu -->
    <% if admin_user? %>
    <!-- make this menu active (expanded) if in the users controller -->
    <li class="<%= 'active' if params[:controller] == 'users' %>">
      <a href="#">
        <span class="sidebar-nav-item-icon fa fa-user fa-lg"></span>
        <span class="sidebar-nav-item">User</span>
        <span class="fa arrow"></span>
      </a>
      <ul>
        <li>
          <%= link_to users_path do %>
            <i class="sidebar-nav-item-icon fa fa-users"></i>All Users
          <% end %>
        </li>
        <li>
          <%= link_to signup_path do %>
             <i class="sidebar-nav-item-icon fa fa-pencil-square-o"></i>New User 
          <% end %>
        </li>
      </ul>
    </li>
    <li class="<%= 'active' if params[:controller] == 'npi_statuses' %>">
      <a href="#">
        <span class="sidebar-nav-item-icon fa fa-flag fa-lg"></span>
        <span class="sidebar-nav-item">MPI Status</span>
        <span class="fa arrow"></span>
      </a>
      <ul>
        <li>
          <%= link_to npi_statuses_path do %>
            <i class="sidebar-nav-item-icon fa fa-flag"></i>All MPI statuses
          <% end %>
        </li>
        <li>
          <%= link_to npi_status_new_path do %>
             <i class="sidebar-nav-item-icon fa fa-pencil-square-o"></i>New MPI Status 
          <% end %>
        </li>
      </ul>
    </li>
    <li class="<%= 'active' if params[:controller] == 'comments' %>">
      <a href="#">
        <span class="sidebar-nav-item-icon fa fa-comment-o fa-lg"></span>
        <span class="sidebar-nav-item">Comment</span>
        <span class="fa arrow"></span>
      </a>
      <ul>
        <li>
          <%= link_to comments_path do %>
            <i class="sidebar-nav-item-icon fa fa-users"></i>All Comments
          <% end %>
        </li>
        <li>
          <%= link_to comment_new_path do %>
             <i class="sidebar-nav-item-icon fa fa-pencil-square-o"></i>New Comment 
          <% end %>
        </li>
      </ul>
    </li>
    <% end %>
  </ul> <!-- end of side menu -->
</nav>
<!-- end of sidebar partial -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <%= render 'layouts/sidebar' %>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <div class="container alert-container
             <%= 'alert-main' if params[:controller] != 'sessions' %>">
            <% flash.each do |key, value| %>
              <% if params[:controller] == 'sessions' %>
                <%= content_tag(:div, class: "alert alert-#{key} alert-signup alert-dismissable") do %>
                  <%= value %>
                  <button type="button" class="close" data-dismiss="alert">&times;</button>
                <% end %>
              <% else %>
                  <%= content_tag(:div, class: "alert alert-#{key} alert-dismissable") do %>
                  <%= value %>
                  <button type="button" class="close" data-dismiss="alert">&times;</button>
                <% end %>
              <% end %>
            <% end %>
          </div>
          <%= yield %>    
          <%= debug(params) if Rails.env.development? %>
        </div>  
      </div>  
    </div>  
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container home-container">
      <div class="container alert-container">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "alert alert-#{key} alert-signup") %>
        <% end %>
      </div>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>